#deploy to Qpon Dev
name: Build and deploy Util Service to qpon development server

on:
  workflow_dispatch:
  push:
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      #run: mvn -B clean install --file pom.xml
      run: mvn clean compile package -DskipTests

    - name: Copy Artifact via scp to aws server
      uses: appleboy/scp-action@master
      env:
        HOST: 13.127.150.136
        USERNAME: qponprod
        PORT: 22
        PASSWORD: QPonpD4
      with:
        source: "./target/qpon-util-service-1.0.1-SNAPSHOT.jar"
        target: "/home/qponprod/"
        