#deploy to Qpon QA
name: Build and deploy Util Service to qpon QA server

on:
  workflow_dispatch:
  push:
    branches: [ qa ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        #run: mvn -B clean install --file pom.xml
        run: mvn clean compile package -DskipTests

      - name: Copy Artifact via scp to aws server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.QA_SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "./target/qpon-util-service-1.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/qpon/services"

      - name: Executing remote command to run the service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
          envs:
            REDIS_PASSWORD:${{ secrets.QA_REDIS_PASS }}
            WEBSMS_API_KEY=${{ secrets.WEBSMS_API_KEY }}
            WEBSMS_API_TOKEN=${{ secrets.WEBSMS_API_TOKEN }}
          #script_stop: true
          script: |
            cd /home/ubuntu/qpon/services/
            sudo su
            NOW=$(date +"%m-%d-%Y-%H-%M")
            declare -i pid
            unset pid
            pid=$(lsof -t -i tcp:8082 -s tcp:listen)
            sudo lsof -t -i tcp:8082 -s tcp:listen | sudo xargs kill
            while [ "$( ps -p ${pid} >/dev/null 2>&1; echo $?)" == "0" ]
            do
              sleep 10s
            done 
            mv qpon-util-service-1.0.1-SNAPSHOT.jar ../logs/bkp/qpon-util-service-1.0.1-SNAPSHOT.jar.$NOW
            mv ../logs/util-service.log ../logs/bkp/util-service.log.$NOW
            mv target/qpon-util-service-1.0.1-SNAPSHOT.jar .
            rm -rf /home/ubuntu/tmp/logs/util-service/*
            export AWS_REGION=ap-southeast-1
            export AWS_EMAIL_SENDER_ID=dev@qpon.lk
            export WEBSMS_API_KEY=${{ secrets.WEBSMS_API_KEY }}
            export WEBSMS_API_TOKEN=${{ secrets.WEBSMS_API_TOKEN }}
            export WEBSMS_SENDER_ID=qpon
            nohup java -jar qpon-util-service-1.0.1-SNAPSHOT.jar > ../logs/util-service.log 2>&1 &
            rm -rf target

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      # this is the new step using the ms-teams-notification action
      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: https://swivelgroup1.webhook.office.com/webhookb2/a625b2a6-af8f-4c61-8083-9cb24dd58fe6@1c9c1873-35f4-41c9-a094-0279b9c8dd76/IncomingWebhook/e566f1d57c774db4be73aa86046cfd5b/bfb54f3b-d6e5-46fd-b97f-964d1bbfee75
          # ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
          notification-summary: Build and deployment to the Qpon QA server went smoothly!  &#x2705;
          notification-color: a317b8
          timezone: America/Denver